import test from 'node:test';import assert from 'node:assert/strict';
import {steerOwnerMessage,prioritizeRequest,requestOrder,workerCapacity} from '../owner-commands.mjs';
import {visibleNotifications} from '../notifications.mjs';
const args={threadId:'task',expectedTurnId:'turn',message:'Use the blue version',requestKey:'owner-message-1'};
function fixture(){return {data:{jobs:[{id:'job',threadId:'task',status:'running',turnId:'turn'}],settings:{concurrency:2}},save(){}};}
test('owner steering is idempotent and never adds a queued job',async()=>{const s=fixture();let calls=0;const services={bridge:{async call(method,p){calls++;assert.equal(method,'turn/steer');assert.equal(p.expectedTurnId,'turn');return {turnId:'turn'}}}};assert.equal((await steerOwnerMessage(s,[],args,services)).status,'steered');assert.equal((await steerOwnerMessage(s,[],args,services)).duplicate,true);assert.equal(calls,1);assert.equal(s.data.jobs.length,1);await assert.rejects(steerOwnerMessage(s,[],{...args,message:'Other'},services),/another message/);});
test('uncertain steering never retries and rejects a changed turn before dispatch',async()=>{const s=fixture();let calls=0;const services={bridge:{async call(){calls++;throw Error('Disconnected')}}};assert.equal((await steerOwnerMessage(s,[],args,services)).status,'uncertain');await steerOwnerMessage(s,[],args,services);assert.equal(calls,1);assert.equal(s.data.jobs.length,1);await assert.rejects(steerOwnerMessage(s,[],{...args,requestKey:'new-receipt',expectedTurnId:'other'},services),/no longer/);assert.equal(calls,1);});
test('desktop steering uses the observed owner and exact active turn',async()=>{const s=fixture();const threads=[{id:'task',activity:{source:'desktop',state:'running',turnId:'desktop-turn'}}];let calls=0;const r=await steerOwnerMessage(s,threads,{...args,expectedTurnId:'desktop-turn'},{desktopControl:{async steerTurn(id,p){calls++;assert.equal(p.expectedTurnId,'desktop-turn');return {turnId:'desktop-turn'}}},bridge:{call(){throw Error('wrong bridge')}}});assert.equal(calls,1);assert.equal(r.status,'steered');});
test('send now prioritizes only undispatched requests with bounded capacity',()=>{const s=fixture();s.data.jobs.push({id:'wait',status:'ready',createdAt:1});const j=prioritizeRequest(s,'wait',10);assert.equal(workerCapacity(j,s.data.settings),8);assert.equal(workerCapacity({kind:'chat'},{concurrency:8}),8);assert.equal([{id:'later',createdAt:0},j].sort(requestOrder)[0].id,'wait');assert.throws(()=>prioritizeRequest(s,'job'),/undispatched/);s.data.settings.paused=true;assert.throws(()=>prioritizeRequest(s,'wait'),/paused/);});
test('completion feed hides voice turns and internal reviews, preserving real Rewster project work',()=>{const threads=[{id:'voice',cwd:'/Users/trey/Library/Application Support/Rewster Local/agent-workspace'},{id:'project',title:'Fix Rewster audio',cwd:'/projects/Rewster'}];const data={jobs:[{id:'review-job',threadId:'review',rewsterReview:{}}],notifications:['voice','project','review'].map(threadId=>({threadId}))};assert.deepEqual(visibleNotifications(data,threads).map(n=>n.threadId),['project']);assert.equal(data.notifications.length,3);});

test('published steering receipts retain their delivery result without resending',async()=>{const s=fixture();s.data.steers=[{requestKey:args.requestKey,signature:JSON.stringify({threadId:args.threadId,expectedTurnId:args.expectedTurnId,prompt:args.message,attachments:[]}),status:'delivered'}];const r=await steerOwnerMessage(s,[],args,{bridge:{call(){throw Error('must not replay')}}});assert.equal(r.status,'steered');assert.equal(r.duplicate,true);});
test('steering photos preserves validated media on the exact active turn',async()=>{const s=fixture();const r=await steerOwnerMessage(s,[],{...args,message:'',attachments:['photo']},{media:{validate(ids){assert.deepEqual(ids,['photo'])},inputs(){return [{type:'localImage',path:'/test/photo.png'}]}},bridge:{async call(method,p){assert.deepEqual(p.input,[{type:'localImage',path:'/test/photo.png'}]);return {turnId:'turn'}}}});assert.equal(r.status,'steered');assert.deepEqual(r.attachments,['photo']);});
