import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../core.mjs';
import {integrationToken,authorizedIntegration,approvalBrief,supervisorSnapshot,sendWorkerMessage,parseReview,queueSupervisorReviews,processReviews} from '../rewster-supervisor.mjs';
function fixture(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'rewster-supervisor-'));try{const store=new Store(path.join(dir,'state.json'));store.data.settings.rewsterSupervisor={enabled:true,autoCorrect:true,enabledAt:1};const [source]=store.accept(['Fix the dashboard layout'],'owner-request',{});Object.assign(source,{threadId:'thread-a',turnId:'turn-a',status:'completed',completedAt:Date.now(),response:'Output: /tmp/result.html',department:'Design'});fn(store,source,dir);}finally{fs.rmSync(dir,{recursive:true,force:true})}}
const findings=[{requirement:'Readable controls',observation:'Text clips',evidence:'/tmp/result.html button width',fix:'Fit the text'}];
const result=source=>JSON.stringify({sourceJobId:source.id,sourceTurnId:source.turnId,verdict:'needs_changes',findings});
test('integration tokens persist and reject missing or wrong credentials',()=>fixture((s,j,dir)=>{const token=integrationToken(dir);assert.equal(integrationToken(dir),token);assert.ok(authorizedIntegration('Bearer '+token,token));assert.equal(authorizedIntegration('',token),false);assert.equal(authorizedIntegration('Bearer nope',token),false);}));
test('approval fingerprint changes when job cost or turn changes',()=>{const a={id:'1',threadId:'a',params:{turnId:'a',cost:100}};assert.notEqual(approvalBrief(a).fingerprint,approvalBrief({...a,params:{...a.params,cost:200}}).fingerprint);assert.equal(approvalBrief(a).ownerHandoff,true)});
test('snapshot does not relabel unknown activity as running or completed work as accepted',()=>{const result=supervisorSnapshot({threads:[{id:'x',activity:{state:'unknown'}}],jobs:[{id:'j',status:'completed'}],settings:{}});assert.equal(result.agents[0].activity.state,'unknown');assert.equal(result.jobs[0].quality,null)});
test('worker messages are idempotent and manual even in full-auto workspace',()=>fixture((s,j)=>{s.data.settings.approvalMode='full-auto';const args={threadId:j.threadId,message:'Check the output',reason:'Owner requested review',requestKey:'message-key-123'};const a=sendWorkerMessage(s,[{id:j.threadId}],args),b=sendWorkerMessage(s,[{id:j.threadId}],args);assert.equal(a.jobId,b.jobId);assert.equal(s.data.jobs.at(-1).approvalMode,'manual');assert.throws(()=>sendWorkerMessage(s,[],args));}));
test('review requires exact source turn and evidence',()=>fixture((s,j)=>{assert.throws(()=>parseReview(result({...j,turnId:'wrong'}),j));assert.throws(()=>parseReview(JSON.stringify({sourceJobId:j.id,sourceTurnId:j.turnId,verdict:'needs_changes',findings:[]}),j));}));
test('reviews are bounded and correction enqueues once on the exact source thread',()=>fixture((s,j)=>{const [review]=queueSupervisorReviews(s,[{model:'gpt-5.6-sol'}]);assert.ok(review.rewsterReview);assert.equal(queueSupervisorReviews(s,[{model:'gpt-5.6-sol'}]).length,0);s.update(review.id,{status:'completed',response:result(j)});processReviews(s);const correction=s.data.jobs.at(-1);assert.equal(correction.options.threadId,j.threadId);assert.equal(correction.correctionRoot,j.id);assert.equal(correction.approvalMode,'manual');const count=s.data.jobs.length;processReviews(s);assert.equal(s.data.jobs.length,count);}));
test('newer owner work prevents stale automatic correction',()=>fixture((s,j)=>{const [review]=queueSupervisorReviews(s,[{model:'gpt-5.6-sol'}]);s.update(review.id,{status:'completed',response:result(j)});const [newer]=s.accept(['New owner direction'],'new-direction',{threadId:j.threadId});Object.assign(newer,{threadId:j.threadId,createdAt:j.createdAt+1});processReviews(s);assert.match(j.quality.ownerAttention,/Newer work/);assert.equal(j.quality.correctionJobId,undefined);}));
test('second correction limit escalates instead of looping',()=>fixture((s,j)=>{const [review]=queueSupervisorReviews(s,[{model:'gpt-5.6-sol'}]);s.update(review.id,{status:'completed',response:result(j)});s.data.jobs.push({id:'c1',correctionRoot:j.id},{id:'c2',correctionRoot:j.id});processReviews(s);assert.match(j.quality.ownerAttention,/Two correction/);}));
test('disabled supervisor and malformed results fail closed',()=>fixture((s,j)=>{s.data.settings.rewsterSupervisor.enabled=false;assert.deepEqual(queueSupervisorReviews(s,[{model:'gpt-5.6-sol'}]),[]);s.data.settings.rewsterSupervisor.enabled=true;const [r]=queueSupervisorReviews(s,[{model:'gpt-5.6-sol'}]);s.update(r.id,{status:'completed',response:'Looks good'});processReviews(s);assert.ok(r.reviewError);assert.equal(j.quality,undefined);}));
